---
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-tsig-secret
  namespace: kube-system
stringData:
  name: externaldns
  secret: e9Y40wFrHQVIBtjy5auUdf2HcIROeWy0X46WqAvhBm4=
---
apiVersion: v1
kind: Secret
metadata:
  name: externaldns-tsig-secret
  namespace: kcm-system
stringData:
  secret: e9Y40wFrHQVIBtjy5auUdf2HcIROeWy0X46WqAvhBm4=
