---
apiVersion: v2
name: cni
type: application
version: 1.0.0
dependencies:
  - name: cilium
    repository: https://helm.cilium.io
    version: 1.17.4
    description: A Helm chart that references official "cilium" Helm chart.
    condition: cilium.install
