---
# Configuration for the Cilium CNI plugin
cilium:
  # Enable or disable the Cilium CNI plugin
  # Set to true to deploy Cilium as the CNI for your Kubernetes cluster.
  enabled: true
  # Whether to install Cilium as part of this chart
  # Set to true to include Cilium installation in this Helm chart deployment.
  install: true

  # Configuration for BGP (Border Gateway Protocol)
  bgp:
    # Enable or disable BGP functionality
    # Set to true to enable BGP for advanced networking use cases.
    enabled: false
    # Node selector for BGP instances (uncomment and configure as needed)
    # Use this to specify which nodes should run BGP instances.
    # nodeSelector:
    #   matchLabels:
    #     rack: rack0
    advert:
      service:
        # Selector for services to advertise (uncomment and configure as needed)
        # Define specific services to advertise via BGP using label selectors.
        # selector:
        #   matchExpressions:
        #     - { key: bgp, operator: In, values: [blue] }
        # Addresses to advertise via BGP
        # Specify the types of IPs to advertise, such as ExternalIP or LoadBalancerIP.
        addresses:
          - ExternalIP
          - LoadBalancerIP
      # Pod CIDR attributes for BGP advertisements (uncomment and configure as needed)
      # Use this section to configure additional attributes for Pod CIDR advertisements.
      # podCIDR:
      #   attributes:
      #     localPreference: 99
      #     communities:
      #       standard: ["65000:99"]

    # Configuration for BGP peers
    peer:
      # Reference to the Kubernetes secret for BGP authentication
      # Specify the name of the secret containing BGP authentication credentials.
      authSecretRef: bgp-cred
      # Enable graceful restart for BGP sessions
      # Set to true to allow BGP sessions to recover gracefully after disruptions.
      gracefulRestart: true
      # Hold time in seconds for BGP sessions
      # The maximum time to wait before considering a BGP session as failed.
      holdTimeSec: 9
      # Keep-alive time in seconds for BGP sessions
      # The interval for sending keep-alive messages to maintain the BGP session.
      keepAliveTimeSec: 3
      # Number of hops allowed for multi-hop BGP sessions
      # Configure the maximum number of hops for BGP multi-hop sessions.
      multiHop: 4
      # Restart time in seconds for BGP sessions
      # The time to wait before restarting a failed BGP session.
      restartTimeSec: 15
      # Address families supported by BGP
      # Define the address families (AFI/SAFI) and their advertisements.
      addressFamilies:
        - afi: ipv4  # Address Family Identifier (AFI) for IPv4.
          safi: unicast  # Subsequent Address Family Identifier (SAFI) for unicast.
          advertisements:
            matchLabels:
              advertise: bgp  # Label to match for advertisements.

    # Instances of BGP configurations
    instances:
      - name: cilium  # Name of the BGP instance
        localASN: 65000  # Local Autonomous System Number (ASN) for this instance.
        overrides:
          enabled: true  # Enable or disable overrides for this instance.
          # Router ID for the instance (uncomment and configure as needed)
          # Specify a unique router ID for the BGP instance.
          # routerID: fd00:10:0:0::1
        peers:
          - name: peer-1  # Name of the BGP peer
            peerASN: 65000  # ASN of the peer
            # Local address for the peer (uncomment and configure as needed)
            # Specify the local address to use for the BGP session with this peer.
            # localAddress: fd00:10:0:0::1
            peerAddress: fd00:10:0:0::1  # Address of the peer
            peerConfigRef:
              name: cni-resources-peer-config  # Reference to the peer configuration.

  # Configuration for Layer 2 (L2) networking
  l2:
    # Enable or disable L2 functionality
    # Set to true to enable Layer 2 networking features.
    enabled: false
    # Advertise external IPs via L2
    # Set to true to allow external IPs to be advertised using Layer 2.
    externalIPs: true
    # Advertise load balancer IPs via L2
    # Set to true to allow load balancer IPs to be advertised using Layer 2.
    loadBalancerIPs: true

  # Configuration for IP address pools
  pool:
    # Enable or disable IP address pooling
    # Set to true to enable the use of IP address pools for assigning IPs.
    enabled: true
    # Allow or disallow the use of the first and last IPs in the pool
    # Set to "Yes" to allow or "No" to disallow the use of the first and last IPs.
    allowFirstLastIPs: "No"
    # CIDR block for the IP address pool
    # Specify the CIDR block to use for the IP address pool.
    cidr: 172.16.0.0/24

  # This section contains configuration values for the Cilium Helm chart.
  # Adjust these values to customize the deployment of Cilium CNI in your Kubernetes cluster.
  kubeProxyReplacement: true  # Enable or disable kube-proxy replacement by Cilium.
  bgpControlPlane:
    enabled: true  # Enable or disable the BGP control plane.
  gatewayAPI:
    enabled: true  # Enable or disable Gateway API support.
  envoy:
    securityContext:
      capabilities:
        keepCapNetBindService: true  # Retain NET_BIND_SERVICE capability for Envoy.
        envoy:
          - NET_ADMIN  # Allow administrative network operations.
          - NET_BIND_SERVICE  # Allow binding to privileged ports.
          - SYS_ADMIN  # Allow system administration operations.
