apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
spec:
  interval: 10m0s
  releaseName: cni
  chart:
    spec:
      chart: cni
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: kcm-system
  values: |
    cilium:
      bgpControlPlane:
        enabled: false
      gatewayAPI:
        gatewayClass:
          create: "true"
          hostNetwork:
            enabled: false
      operator:
        replicas: 1
      pool:
        enabled: true
