apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi
spec:
  interval: 10m0s
  releaseName: csi
  chart:
    spec:
      chart: csi
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
        namespace: kcm-system
  values: |
    openebs:
      csi:
        volumeSnapshots:
          enabled: true
          keep: false
      localpv-provisioner:
        hostpathClass:
          name: general
