---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Management
metadata:
  name: kcm
  labels:
    k0rdent.mirantis.com/component: kcm
spec:
  release: kcm-1-1-1
  providers:
    - name: cluster-api-provider-docker
    - name: cluster-api-provider-k0sproject-k0smotron
    - name: projectsveltos
    # - name: cluster-api-provider-aws
    # - name: cluster-api-provider-azure
    # - name: cluster-api-provider-gcp
    # - name: cluster-api-provider-infoblox
    # - name: cluster-api-provider-ipam
    # - name: cluster-api-provider-openstack
    # - name: cluster-api-provider-vsphere
  core:
    capi: {}
    kcm:
      config:
        replicas: 1
        controller:
          enableTelemetry: false
          templatesRepoURL: oci://ghcr.io/k0rdent/kcm/charts
        image:
          repository: ghcr.io/k0rdent/kcm/controller
          tag: 1.1.1
        cert-manager:
          enableCertificateOwnerRef: true
          # config:
          #   apiVersion: controller.config.cert-manager.io/v1alpha1
          #   kind: ControllerConfiguration
          #   enableGatewayAPI: true
        flux2:
          kustomizeController:
            create: true
            container:
              additionalArgs:
                - --watch-label-selector=k0rdent.mirantis.com/managed=true
          sourceController:
            persistence:
              enabled: true
