---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Management
metadata:
  name: kcm
  labels:
    k0rdent.mirantis.com/component: kcm
spec:
  release: kcm-1-0-0
  providers:
    - name: cluster-api-provider-docker
    - name: cluster-api-provider-k0sproject-k0smotron
    - name: projectsveltos
    # - name: cluster-api-provider-aws
    # - name: cluster-api-provider-azure
    # - name: cluster-api-provider-gcp
    # - name: cluster-api-provider-infoblox
    # - name: cluster-api-provider-ipam
    # - name: cluster-api-provider-openstack
    # - name: cluster-api-provider-vsphere
  # core:
  #   capi: {}
  #   kcm:
  #     config:
  #       cert-manager:
  #         config:
  #           apiVersion: controller.config.cert-manager.io/v1alpha1
  #           enableGatewayAPI: true
  #           kind: ControllerConfiguration
  #         crds:
  #           enabled: true
  #           keep: false
  #         enableCertificateOwnerRef: true
  #       controller:
  #         enableTelemetry: false
  #       flux2:
  #         helmController:
  #           container:
  #             additionalArgs:
  #               - '--watch-label-selector=k0rdent.mirantis.com/managed=true'
  #           create: true
  #         kustomizeController:
  #           container:
  #             additionalArgs:
  #               - '--watch-label-selector=k0rdent.mirantis.com/managed=true'
  #           create: true
  #         sourceController:
  #           container:
  #             additionalArgs:
  #               - '--watch-label-selector=k0rdent.mirantis.com/managed=true'
  #           create: true
  #           persistence:
  #             enabled: true
  #       replicas: 1
