---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: cert-manager-1-17-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cert-manager
      version: 1.17.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: labsonline-catalog
