---
apiVersion: v2
type: application
name: cert-manager
description: A Helm chart that deploys cert-manager and its dependencies.
version: 1.17.2
dependencies:
  - name: ca-clusterissuer
    description: A Helm chart that references official "ca-clusterissuer" Helm chart.
    version: 0.2.0
    condition: ca-clusterissuer.enabled
  - name: ca-issuer
    description: A Helm chart that references official "ca-issuer" Helm chart.
    version: 0.3.0
    condition: ca-issuer.enabled
  - name: cert-manager
    repository: https://charts.jetstack.io
    description: A Helm chart that references official "cert-manager" Helm chart.
    version: 1.17.2
    condition: cert-manager.enabled
  - name: trust-manager
    repository: https://charts.jetstack.io
    description: A Helm chart that references official "trust-manager" Helm chart.
    version: 0.17.1
    condition: trust-manager.enabled
