---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: dev-openstack
  namespace: default
spec:
  template: openstack-cluster-0-0-1
  credential: openstack-cluster-cred
  propagateCredentials: false
  config:
    clusterLabels:
      app.kubernetes.io/cni: cilium
      app.kubernetes.io/csi: openebs
    k0s:
      api:
        sans:
          - openstack.kubernetes.local
      network:
        provider: custom
      featureGates:
        - name: UserNamespacesSupport
          enabled: true
  serviceSpec:
    services: []
    # - template: svc-1-0-0
    #   name: svc
    #   namespace: default
