---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: dev-remote
  namespace: default
spec:
  template: remote-cluster-1-0-8
  credential: remote-cluster-cred
  propagateCredentials: false
  config:
    controlPlaneNumber: 1
    clusterLabels: {}
    k0smotron:
      service:
        type: NodePort
    k0s:
      api:
        sans:
          - remote.kubernetes.local
      network:
        provider: custom
      featureGates:
        - name: UserNamespacesSupport
          enabled: true
      helm:
        charts:
          - name: cni
            chartname: oci://ghcr.io/labsonline/charts/cni
            namespace: kube-system
            version: 1.0.0
            values: |
              cilium:
                kubeProxyReplacement: true
                bgpControlPlane:
                  enabled: false
                gatewayAPI:
                  gatewayClass:
                    create: "true"
                    hostNetwork:
                      enabled: true
                pool:
                  enabled: true
                  allowFirstLastIPs: No
                  cidr: 172.16.254.0/24
                operator:
                  replicas: 1
                envoy:
                  securityContext:
                    capabilities:
                      keepCapNetBindService: true
                      envoy:
                        - NET_ADMIN
                        - NET_BIND_SERVICE
                        - SYS_ADMIN
          - name: csi
            chartname: oci://ghcr.io/labsonline/charts/csi
            namespace: kube-system
            version: 1.0.0
            values: |
              ceph:
                enabled: false
              openebs:
                csi:
                  volumeSnapshots:
                    enabled: true
                    keep: false
                localpv-provisioner:
                  hostpathClass:
                    name: general
  serviceSpec:
    services: []
    # - template: knative-1-0-0
    #   name: knative
    #   namespace: kcm-system
