---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: dev-remote
  namespace: default
spec:
  template: remote-cluster-1-0-0
  credential: remote-cluster-cred
  propagateCredentials: false
  config:
    controlPlaneNumber: 1
    clusterLabels:
      app.kubernetes.io/cni: cilium
      app.kubernetes.io/csi: openebs
    k0smotron:
      service:
        type: NodePort
    k0s:
      api:
        sans:
          - remote.kubernetes.local
      network:
        provider: custom
      featureGates:
        - name: UserNamespacesSupport
          enabled: true
      helm:
        charts:
          - name: cni
            chartname: oci://registry-1.docker.io/labsonline/charts/cni
            namespace: kube-system
            version: 1.0.0
    machines:
      - address: 10.211.55.3
        user: parallels # The user must have root permissions
        port: 22
  serviceSpec:
    services:
      - template: cni-1-0-0
        name: cni
        namespace: kube-system
        values: |
          cilium:
            bgpControlPlane:
              enabled: false
            gatewayAPI:
              gatewayClass:
                create: "true"
                hostNetwork:
                  enabled: true
            pool:
              enabled: true
              allowFirstLastIPs: No
              cidr: 172.16.252.0/24
            operator:
              replicas: 1
