---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: dev-docker
  namespace: default
spec:
  dryRun: false
  template: docker-hosted-cp-1-0-0
  credential: docker-cluster-cred
  propagateCredentials: false
  config:
    clusterLabels:
      app.kubernetes.io/cni: cilium
      app.kubernetes.io/csi: openebs
    k0s:
      api:
        sans:
          - docker.kubernetes.local
      network:
        provider: custom
      featureGates:
        - name: UserNamespacesSupport
          enabled: true
      helm:
        charts:
          - name: cni
            chartname: oci://registry-1.docker.io/labsonline/charts/cni
            namespace: kube-system
            version: 1.0.0
            values: |
              cilium:
                kubeProxyReplacement: true
                bgpControlPlane:
                  enabled: false
                gatewayAPI:
                  gatewayClass:
                    create: "true"
                    hostNetwork:
                      enabled: true
                pool:
                  enabled: true
                  allowFirstLastIPs: No
                  cidr: 172.16.254.0/24
                operator:
                  replicas: 1
                envoy:
                  securityContext:
                    capabilities:
                      keepCapNetBindService: true
                      envoy:
                        - NET_ADMIN
                        - NET_BIND_SERVICE
                        - SYS_ADMIN
          - name: csi
            chartname: oci://registry-1.docker.io/labsonline/charts/cni
            namespace: kube-system
            version: 1.0.0
            values: |
              openebs:
                csi:
                  volumeSnapshots:
                    enabled: true
                    keep: false
                localpv-provisioner:
                  hostpathClass:
                    name: general
  serviceSpec:
    services: []
    # - template: svc-1-0-0
    #   name: svc
    #   namespace: default
