{{- if and .Values.cilium.enabled .Values.cilium.bgp.enabled }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: {{ include "cni-resources.fullname" . }}-advert
  labels:
    {{- include "cni-resources.labels" . | nindent 4 }}
    {{- range .Values.cilium.bgp.peer.addressFamilies }}
    {{- .advertisements.matchLabels | toYaml | nindent 4 }}
    {{- end }}
spec:
  advertisements:
    {{-  if .Values.cilium.bgp.advert.service }}
    - advertisementType: "Service"
      {{- if .Values.cilium.bgp.advert.service.selector }}
      selector: {{ .Values.cilium.bgp.advert.service.selector | toYaml | nindent 12 }}
      {{- end }}
      service:
        addresses: {{ .Values.cilium.bgp.advert.service.addresses | toYaml | nindent 12 }}
    {{- end }}
    {{-  if .Values.cilium.bgp.advert.podCIDR }}
    - advertisementType: PodCIDR
      attributes: {{ .Values.cilium.bgp.advert.podCIDR.attributes | toYaml | nindent 10 }}
    {{- end }}
{{- end }}
