{{- if and .Values.cilium.enabled .Values.cilium.pool.enabled }}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: {{ include "cni-resources.fullname" . }}-ip-pool
  labels:
    {{- include "cni-resources.labels" . | nindent 4 }}
spec:
  allowFirstLastIPs: {{ .Values.cilium.pool.allowFirstLastIPs | quote }}
  blocks:
    - cidr: {{ .Values.cilium.pool.cidr }}
{{- end }}
