---
services:
  kcm:
    image: ghcr.io/labsonline/devcontainer:24.04
    container_name: devbox
    hostname: devbox
    network_mode: bridge # only supported mode
    privileged: true # required by /sbin/init
    stdin_open: true
    tty: true
    user: root # required by /sbin/init
    working_dir: /home/ubuntu/workspace
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ../:/home/ubuntu/workspace
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
      - ~/.zshrc:/home/ubuntu/.zshrc:ro
      - /dev/kmsg:/dev/kmsg:ro # required by kubelets OOM watcher
      - /lib/modules:/lib/modules:ro # required by cylium
      - /var/lib/k0s
      - /var/log/pods
      # NOTE: The following are not needed for the devcontainer to work.
      # - ~/.gnupg:/home/ubuntu/.gnupg:ro
      # - ~/.ssh:/home/ubuntu/.ssh:ro
    ports:
      - 30443:30443
      - 443:443
      - 6443:6443
      - 80:80
