---
services:
  kcm:
    container_name: kcm
    hostname: kcm
    network_mode: bridge # only supported mode
    privileged: true # required by /sbin/init
    stdin_open: true
    tty: true
    user: root # required by /sbin/init
    working_dir: /home/devcontainer/workspace
    build:
      context: .
      dockerfile: Dockerfile
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ../:/home/devcontainer/workspace
      - ../hack/containerd.toml:/etc/k0s/containerd.d/systemd.toml:ro
      - ./authorized_keys:/home/devcontainer/.ssh/authorized_keys:ro
      - ./crds:/var/lib/k0s/manifests/crds:ro
      - /dev/kmsg:/dev/kmsg:ro # required by kubelets OOM watcher
      - /lib/modules:/lib/modules:ro # required by cylium
      - /var/lib/k0s
      - /var/log/pods
    ports:
      - 10022:22
      - 30443:30443
      - 443:443
      - 6443:6443
      - 80:80
