---
namespace: kcm-system
buildMetadata:
  - managedByLabel
  - originAnnotations
commonLabels:
  k0rdent.mirantis.com/managed: "true"
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ca.yaml
  - crd.yaml
  - edns.yaml
  - gateway.yaml
  - knative.yaml
