---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: mgmt-mcs
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/management-cluster: "true"
      sveltos-agent: present
  serviceSpec:
    priority: 100
    services:
      - template: external-snapshotter-crd
        name: external-snapshotter-crd
        namespace: kube-system
      - template: gateway-api-experimental-crd
        name: gateway-api-experimental-crd
        namespace: kube-system
      - template: cni-1-0-0
        name: cni
        namespace: kube-system
        values: |
          cilium:
            bgpControlPlane:
              enabled: false
            gatewayAPI:
              gatewayClass:
                create: "true"
                hostNetwork:
                  enabled: true
            operator:
              replicas: 1
      - template: csi-1-0-0
        name: csi
        namespace: kube-system
        values: |
          openebs:
            csi:
              volumeSnapshots:
                enabled: true
                keep: false
          localpv-provisioner:
            hostpathClass:
              name: general
