---
namespace: kcm-system
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
resources:
  - adopted
  - docker
  - openstack
  - remote
  - vsphere
