---
namespace: kcm-system
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
  labels:
    k0rdent.mirantis.com/component: kcm
  annotations:
    projectsveltos.io/template: "true"
configmapGenerator:
  - name: remote-cluster-config
secretGenerator:
  - name: remote-cluster-secret
    envs:
      - .env
resources:
  - credential.yaml
  - remote-cluster.yaml
