---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-catalog
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  type: oci
  url: oci://docker.io/bitnami/charts
