---
namespace: kcm-system
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
  labels:
    k0rdent.mirantis.com/component: kcm
  annotations:
    projectsveltos.io/template: "true"
secretGenerator:
  - name: vsphere-cluster-secret
resources:
  - credential.yaml
  - vsphere-standalone-cp.yaml
