---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: cni
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/cni: cilium
  serviceSpec:
    priority: 100
    services:
      - template: cni-1-0-0
        name: cni
        namespace: kube-system
        values: |
          kubeProxyReplacement: true
          bgpControlPlane:
            enabled: false
          gatewayAPI:
            enabled: true
            gatewayClass:
              create: "true"
              hostNetwork:
                enabled: true
          envoy:
            securityContext:
              capabilities:
                keepCapNetBindService: true
                envoy:
                  - NET_ADMIN
                  - NET_BIND_SERVICE
                  - SYS_ADMIN
