---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: csi
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/csi: openebs
  serviceSpec:
    priority: 100
    services:
      - template: csi-1-0-0
        name: csi
        namespace: kube-system
        values: |
          openebs:
            csi:
              volumeSnapshots:
                enabled: true
                keep: false
          localpv-provisioner:
            hostpathClass:
              name: general
