---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: crd
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  serviceSpec:
    priority: 100
    services:
      - template: external-snapshotter-crd
        name: external-snapshotter-crd
        namespace: kube-system
      - template: gateway-api-crd
        name: gateway-api-crd
        namespace: kube-system
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: global
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  serviceSpec:
    priority: 100
    services:
      - template: ca-1-0-2
        name: ca
        namespace: cert-manager
        values: |
          cert-manager:
            enabled: true
            enableCertificateOwnerRef: true
            crds:
              enabled: true
            config:
              apiVersion: controller.config.cert-manager.io/v1alpha1
              kind: ControllerConfiguration
              enableGatewayAPI: true
      - template: edns-1-0-2
        name: edns
        namespace: kube-system
        values: |
          endpoints: []
          # - name: examplearecord
          #   records:
          #     - name: example.com
          #       targets:
          #         - 10.0.0.1
          external-dns:
            enabled: true
      - template: gateway-1-0-2
        name: gateway
        namespace: kube-system
