---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: crd
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  serviceSpec:
    priority: 100
    services:
      - template: external-snapshotter-crd
        name: external-snapshotter-crd
        namespace: kube-system
      - template: gateway-api-crd
        name: gateway-api-crd
        namespace: kube-system
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: global
spec:
  clusterSelector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  serviceSpec:
    priority: 100
    services:
      - template: ca-1-0-0
        name: ca
        namespace: cert-manager
      - template: edns-1-0-0
        name: edns
        namespace: kube-system
      - template: gateway-1-0-0
        name: gateway
        namespace: kube-system
