---
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
resources:
  - mgmt
  - component/cloudcontroller
  - component/cloudvisor
  - component/codecloud
  - profile/cruiser
  - profile/harbor
  - global.yaml
